### ISSUE TITLE
gopls 0.6.10 snap broken on Debian Buster

### ISSUE THREAD

**Issue by js-sketch** [alexmurray/gopls-snap#3] opened 2021-04-27 07:24 UTC
Hi!

Your snap is broken for me on Debian Buster.

To reproduce:

```
sudo snap install --edge gopls --classic
gopls
```

Expected output: Nothing. `gopls` starts executing.

Actual output:

```
*** stack smashing detected ***: <unknown> terminated
```

This does not occur on gopls when installed with `go get`.

**Comment by alexmurray** [comment] 2021-04-27 12:07
Thanks for reporting this issue - I can reproduce it locally on Ubuntu 21.04 so I'll see what can be done...

**Comment by alexmurray** [comment] 2021-04-28 06:45
I suspect this is a result of https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1926355, will try switching to a `core18` base for now and see if this helps.

**Comment by alexmurray** [comment] 2021-04-29 01:57
This seems to be fixed in the core20 snap and so I have rebuilt gopls 0.6.10 on the edge channel and it works now for me without issue - can you please retest and see if it is any better on Debian for you?

**Comment by js-sketch** [comment] 2021-04-29 07:10
It works for me!

**Comment by alexmurray** [comment] 2021-04-29 07:47
Excellent, I'll close this issue then.

**Closed as completed by alexmurray** 2021-04-29 07:47 UTC

**Comment by js-sketch** [comment] 2021-04-29 07:48
Thank you for your work and time :).
